/**
 * (C) Copyright IBM Corporation 2021, 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.openliberty.tools.gradle.tasks


import io.openliberty.tools.common.plugins.config.ServerConfigXmlDocument
import io.openliberty.tools.common.plugins.config.XmlDocument
import io.openliberty.tools.common.plugins.util.FeatureGeneratorUtil
import static io.openliberty.tools.common.plugins.util.FeatureGeneratorUtil.*;
import io.openliberty.tools.common.plugins.util.PluginExecutionException
import io.openliberty.tools.common.plugins.util.ServerFeatureUtil
import io.openliberty.tools.common.plugins.util.ServerFeatureUtil.FeaturesPlatforms
import io.openliberty.tools.common.plugins.util.VersionUtility;
import io.openliberty.tools.gradle.utils.ArtifactDownloadUtil

import org.gradle.api.artifacts.Configuration
import org.gradle.api.GradleException
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.options.Option
import org.gradle.api.logging.LogLevel
import org.xml.sax.SAXException
import org.w3c.dom.Element;
import org.apache.maven.artifact.versioning.ComparableVersion

import javax.xml.parsers.ParserConfigurationException
import javax.xml.transform.TransformerException

class GenerateFeaturesTask extends AbstractFeatureTask {

    public static final String HEADER = "This file was generated by the Liberty Gradle Plugin and will be overwritten on subsequent runs of the generateFeatures task." + "\n It is recommended that you do not edit this file.";
    public static final String GENERATED_FEATURES_COMMENT = "The following features were generated based on API usage detected in your application";
    public static final String NO_NEW_FEATURES_COMMENT = "No additional features generated";
    public static final String NO_CLASS_FILES_WARNING = "Could not find class files to generate features against. Liberty features will not be generated. Ensure your project has first been compiled.";
    public static final String VERSIONLESS_FEATURE_DETECTED_DEVMODE = "Versionless features are detected in the server configuration. " \
            + "If you would like to continue using the automatic generation of features, remove all versionless features from your server configuration. " \
            + "If you would like to continue using versionless features, you can disable the automatic generation of features.";
    public static final String VERSIONLESS_FEATURE_DETECTED = "Versionless features are detected in the server configuration. " \
            + "To use the 'generate-features' goal, remove all versionless features from your server configuration. " \
            + "If you would like to continue using versionless features, you cannot use the 'generate-features' goal.";
    private static final String OPEN_LIBERTY_PRODUCT_ID = "io.openliberty";
    private static final String WEBSPHERE_LIBERTY_PRODUCT_ID = "com.ibm.websphere.appserver.runtime";

    // Default value of the optimize task option
    private static final boolean DEFAULT_OPTIMIZE = true;
    // Default value of the generateToSrc option
    private static final boolean DEFAULT_GENERATETOSRC = false;
    // Default value of the useTempDirAsOutput option
    private static final boolean DEFAULT_OUTPUT = false;
    // Default value of the useTempDirAsContext option
    private static final boolean DEFAULT_CONTEXT = false;

    /**
     * Generating features is performed relative to a certain server. We only generate features
     * that are missing from a server config. By default we generate features that are missing
     * from the server directory in build/wlp/usr/servers/<server name>.
     * If generateToSrc is specified then we generate features which are missing from the Liberty
     * config specified in the src directory src/main/liberty/config.
     * We will select one server config as the context of this operation.
     */
    private File generationContextDir;

    /**
     * Liberty features are generated in the context of a certain server and they are stored in
     * an XML file in the configDir, the serverDir or a temporary directory. When using dev
     * mode we must write to the tempDir and call install-features before we can use the
     * features in the running server. When not using dev mode we can just write the features
     * to the configDir or serverDir as indicated by the generateToSrc option.
     */
    private File generationOutputDir;

    GenerateFeaturesTask() {
        configure({
            description = 'Generate the features used by an application and add to the configuration of a Liberty server'
            group = 'Liberty'
        })
    }

    private List<String> classFiles = null;

    @Option(option = 'classFile', description = 'If set and optimize is false, will generate features for the list of classes passed.')
    void setClassFiles(List<String> classFiles) {
        this.classFiles = classFiles;
    }

    private Boolean optimize = null;

    // Need to use a string value to allow the ability to specify a value for the parameter (ie. --optimize=false)
    @Option(option = 'optimize', description = 'Optimize generating features by passing in all classes and only user specified features.')
    void setOptimize(String optimize) {
        this.optimize = Boolean.parseBoolean(optimize);
    }

    private Boolean generateToSrc = null;

    // Need to use a string value to allow the ability to specify a value for the parameter (ie. --generateToSrc=false)
    @Option(option = 'generateToSrc', description = 'Generate features to a file in the project\'s src directory')
    void setGenerateToSrc(String generateToSrc) {
        this.generateToSrc = Boolean.parseBoolean(generateToSrc);
    }

    private Boolean useTempDirAsOutput = null;

    /**
     * The useTempDirAsOutput parameter is for internal use only. It is not for users.
     * The parameter is only used when generateToSrc is false meaning we generate to serverDir.
     * It is needed in dev mode because the server is running and we need to ensure the features
     * that are generated are installed before we update a running server.
     * When the parameter is true we will write the generated features file to the special generate-features
     * temp directory.
     */
    @Option(option = 'useTempDirAsOutput', description = 'Internal only option indicating where dev mode is to generate features')
    void setUseTempDirAsOutput(String useTempDirAsOutput) {
        this.useTempDirAsOutput = Boolean.parseBoolean(useTempDirAsOutput);
    }

    private Boolean useTempDirAsContext = null;

    /**
     * The useTempDirAsContext parameter is for internal use only. It is not for users.
     * It is needed in dev mode when the user updates a server config file which might affect
     * the features that will be generated. In such a case we will required the caller to copy the
     * serverDir configuration files into the special generate-features temp directory and augment it
     * with the file changed by the user. We do not do this all the time because of the performance
     * cost of copying all the files.
     * When the parameter is true we will use the generate-features temp directory as the context for
     * feature generation.
     */
    @Option(option = "useTempDirAsContext", description = 'Internal only option indicating how dev mode is to generate features')
    void setUseTempDirAsContext(String useTempDirAsContext) {
        this.useTempDirAsContext = Boolean.parseBoolean(useTempDirAsContext);
    }

    private Boolean isDevMode = null;

    /**
     * The isDevMode parameter is for internal use only. It is not for users.
     * This option must only be set to true when this task is called from dev mode and false otherwise.
     * This option is added to support generateToSrc and to cause writing the generated features file
     * to the server directory (if it exists) in stand-alone mode (not dev mode) in order to save the user
     * having to copy it manually.
     */
    @Option(option = 'isDevMode', description = 'Internal only option indicating dev mode is active')
    void setIsDevMode(String devModeArg) {
        this.isDevMode = Boolean.parseBoolean(devModeArg);
    }

    @TaskAction
    void generateFeatures() {
        // The executable file used to scan binaries for the Liberty features they use.
        File featureGenJar = getFeatureGenJarFromRepository();
        FeatureGenHandler featureGenHandler = new FeatureGenHandler(featureGenJar);

        if (optimize == null) {
            optimize = DEFAULT_OPTIMIZE;
        }
        if (generateToSrc == null) {
            generateToSrc = DEFAULT_GENERATETOSRC;
        }
        if (useTempDirAsOutput == null) {
            useTempDirAsOutput = DEFAULT_OUTPUT;
        }
        if (useTempDirAsContext == null) {
            useTempDirAsContext = DEFAULT_CONTEXT;
        }
        if (isDevMode == null) {
            isDevMode = DEFAULT_ISDEVMODE;
        }

        initializeConfigDirectory();
        if (useTempDirAsContext) {
            // When this parameter is true it is required that the caller has copied the config into this dir.
            generationContextDir = getGeneratedFeaturesTempDir();
        } else {
            // The server.configDirectory is the one in the src directory. Otherwise generate for the build/wlp dir.
            generationContextDir = generateToSrc ? server.configDirectory : getServerDir(project);
        }
        // When using dev mode we always generate to a temporary directory so we can call install before writing to server dir.
        generationOutputDir = useTempDirAsOutput ? getGeneratedFeaturesTempDir() : generationContextDir;

        logger.debug("--- Generate Features values ---");
        logger.debug("optimize generate features: " + optimize);
        logger.debug("generate from src or build: " + generationContextDir);
        logger.debug("useTempDirAsOutput (dev mode only): " + useTempDirAsOutput);
        logger.debug("useTempDirAsContext (dev mode only): " + useTempDirAsContext);
        logger.debug("generate to directory: " + generationOutputDir.getAbsolutePath());
        if (classFiles != null && !classFiles.isEmpty()) {
            logger.debug("Generate features for the following class files: " + classFiles);
        }

        // TODO add support for env variables
        // commented out for now as the current logic depends on the server dir existing and specifying features with env variables is an edge case
        /* def serverDirectory = getServerDir(project);
        def libertyDirPropertyFiles;
        try {
            libertyDirPropertyFiles = getLibertyDirectoryPropertyFiles(getInstallDir(project), getUserDir(project), serverDirectory);
        } catch (IOException x) {
            logger.debug("Exception reading the server property files", e);
            logger.error("Error attempting to generate server feature list. Ensure your user account has read permission to the property files in the server installation directory.");
            return;
        } */

        // Detect if there is a generate-features.xml file in src already when generating to server dir
        if (!generateToSrc && new File(server.configDirectory, GENERATED_FEATURES_FILE_PATH).exists()) {
            if (isDevMode) { // this is serious because dev mode will overwrite the generated file when copying from src
                logger.error("A 'generated-features.xml' file was detected in the source Liberty configuration directory. " +
                    "It will overwrite the file generated to the server directory by the automatic generation of features. " +
                    "To continue to generate features to the server directory, you must delete the 'generated-features.xml' file " +
                    "in the source Liberty configuration directory. To generate features to the source Liberty configuration " +
                    "directory instead, you can type 's' + Enter.");
            } else { // command line task just a warning that this configuration is not expected
                logger.warn("A 'generated-features.xml' file was detected in the source Liberty configuration directory. " +
                    "To generate features to the server directory, it is recommended you delete the 'generated-features.xml' " +
                    "file in the source Liberty configuration directory. To generate features to the source Liberty " +
                    "configuration directory, you must use the option --generateToSrc=true.");
            }
        }
 
        // get existing server features from source directory
        ServerFeatureUtil servUtil = getServerFeatureUtil(true, null);
        Set<String> generatedFiles = new HashSet<String>();
        generatedFiles.add(GENERATED_FEATURES_FILE_NAME);

        Set<String> existingFeatures = getServerFeatures(servUtil, generatedFiles, optimize);
        logger.debug("Existing features:" + existingFeatures);
        Set<String> nonCustomFeatures = new HashSet<String>(); // feature generator only handles actual Liberty features
        for (String feature : existingFeatures) { // custom features are "usr:feature-1.0" or "myExt:feature-2.0"
            if (!feature.contains(":")) nonCustomFeatures.add(feature);
        }
        logger.debug("Non-custom features:" + nonCustomFeatures);

        Set<String> scannedFeatureList;
        String eeVersion = null;
        String mpVersion = null;
        try {
            Set<String> directories = getClassesDirectories();
            if (directories.isEmpty() && (classFiles == null || classFiles.isEmpty())) {
                // log as warning and continue to call feature generator to detect conflicts in user specified features
                logger.warn(NO_CLASS_FILES_WARNING);
            }
            eeVersion = getEEVersion(project, servUtil);
            mpVersion = getMPVersion(project, servUtil);

            String logLocation = project.getBuildDir().getCanonicalPath();
            String eeVersionArg = composeEEVersion(eeVersion);
            String mpVersionArg = composeMPVersion(mpVersion);
            Map featureListFileMap = new HashMap<String, File>();
            String libertyGroupId = getLibertyRuntimeGroupId();
            logger.debug("Resolve the liberty groupId used to fetch feature lists, getLibertyRuntimeGroupId()="+libertyGroupId);
            if (WEBSPHERE_LIBERTY_PRODUCT_ID.equals(libertyGroupId)) {
                File baseFeatureListFile = getWebSphereFeatureListFile(FEATURE_LIST_BASE);
                featureListFileMap.put(WSBASE_FEATURELIST_KEY, baseFeatureListFile);
                File coreFeatureListFile = getWebSphereFeatureListFile(FEATURE_LIST_CORE);
                featureListFileMap.put(WSCORE_FEATURELIST_KEY, coreFeatureListFile);
            } else if (OPEN_LIBERTY_PRODUCT_ID.equals(libertyGroupId)) {
                File featureListFile = getOpenFeatureListFile();
                featureListFileMap.put(OL_FEATURELIST_KEY, featureListFile);
                // Also pass the Base featurelist when using Open Liberty to work around a bug in the feature-gen jar
                File baseFeatureListFile = getWebSphereFeatureListFile(FEATURE_LIST_BASE);
                featureListFileMap.put(WSBASE_FEATURELIST_KEY, baseFeatureListFile);
            } // else should not happen, just pass empty map
            scannedFeatureList = featureGenHandler.runFeatureGenerator(nonCustomFeatures, classFiles, directories, logLocation,
                eeVersionArg, mpVersionArg, featureListFileMap, optimize);
        } catch (FeatureGeneratorUtil.NoRecommendationException noRecommendation) {
            throw new GradleException(String.format(FeatureGeneratorUtil.FEATURE_GEN_CONFLICT_MESSAGE3, noRecommendation.getConflicts()));
        } catch (FeatureGeneratorUtil.FeatureModifiedException featuresModified) {
            Set<String> userFeatures = (optimize) ? existingFeatures :
                getServerFeatures(servUtil, generatedFiles, true); // user features excludes generatedFiles
            Set<String> modifiedSet = featuresModified.getFeatures(); // a set that works after being modified by the generator

            if (modifiedSet.containsAll(userFeatures)) {
                // none of the user features were modified, only features which were generated earlier.
                logger.debug("FeatureModifiedException, modifiedSet containsAll userFeatures, pass modifiedSet on to generateFeatures");
                // features were modified to get a working set with the application's API usage, display warning to users and use modified set
                logger.warn(featuresModified.getMessage());
                scannedFeatureList = modifiedSet;
            } else {
                Set<String> allAppFeatures = featuresModified.getSuggestions(); // suggestions are scanned from binaries
                allAppFeatures.addAll(userFeatures); // scanned plus configured features were detected to be in conflict
                logger.debug("FeatureModifiedException, combine suggestions from generator with user features in error msg");
                throw new GradleException(String.format(FeatureGeneratorUtil.FEATURE_GEN_CONFLICT_MESSAGE1, allAppFeatures, modifiedSet));
            }
        } catch (FeatureGeneratorUtil.RecommendationSetException showRecommendation) {
            if (showRecommendation.isExistingFeaturesConflict()) {
                throw new GradleException(String.format(FeatureGeneratorUtil.FEATURE_GEN_CONFLICT_MESSAGE2, showRecommendation.getConflicts(), showRecommendation.getSuggestions()));
            }
            throw new GradleException(String.format(FeatureGeneratorUtil.FEATURE_GEN_CONFLICT_MESSAGE1, showRecommendation.getConflicts(), showRecommendation.getSuggestions()));
        } catch (FeatureGeneratorUtil.FeatureUnavailableException featureUnavailable) {
            throw new GradleException(String.format(FeatureGeneratorUtil.FEATURE_GEN_CONFLICT_MESSAGE5, featureUnavailable.getConflicts(), featureUnavailable.getMPLevel(),
                    featureUnavailable.getEELevel(), featureUnavailable.getUnavailableFeatures()));
        } catch (FeatureGeneratorUtil.IllegalTargetComboException illegalCombo) {
            throw new GradleException(String.format(FeatureGeneratorUtil.FEATURE_GEN_INVALID_COMBO_MESSAGE, eeVersion, mpVersion));
        } catch (FeatureGeneratorUtil.IllegalTargetException illegalTargets) {
            String messages = buildInvalidArgExceptionMessage(illegalTargets.getEELevel(), illegalTargets.getMPLevel(), eeVersion, mpVersion);
            throw new GradleException(messages);
        } catch (BinaryScannerUtil.VersionlessFeatureDetectedException versionless) {
            throw new GradleException(isDevMode ? VERSIONLESS_FEATURE_DETECTED_DEVMODE : VERSIONLESS_FEATURE_DETECTED);
        } catch (PluginExecutionException x) {
            // throw an error when there is a problem not caught in runFeatureGenerator()
            Object o = x.getCause();
            if (o != null) {
                logger.debug("Caused by exception:" + x.getCause().getClass().getName());
                logger.debug("Caused by exception message:" + x.getCause().getMessage());
            }
            throw new GradleException("Failed to generate a working set of features. " + x.getMessage(), x);
        }

        def missingLibertyFeatures = new HashSet<String>();
        if (scannedFeatureList != null) {
            missingLibertyFeatures.addAll(scannedFeatureList);

            servUtil.setLowerCaseFeatures(false);
            // get set of user defined features so they can be omitted from the generated file that will be written
            Set<String> userDefinedFeatures = optimize ? existingFeatures : new HashSet<String>();
            if (!optimize) {
                FeaturesPlatforms fp = servUtil.getServerFeatures(generationContextDir, server.serverXmlFile, new HashMap<String, File>(), generatedFiles);
                if (fp != null) {
                    userDefinedFeatures = fp.getFeatures();
                }
            }
            logger.debug("User defined features:" + userDefinedFeatures);
            servUtil.setLowerCaseFeatures(true);
            if (!userDefinedFeatures.isEmpty()) {
                missingLibertyFeatures.removeAll(userDefinedFeatures);
            }
        }
        logger.debug("Features detected by feature generator which are not in server.xml : " + missingLibertyFeatures);

        // generate the new features into an xml file in the correct context directory
        def generatedXmlFile;
        if (internalDevMode) {
            // create a temp dir in the build directory for the generated-features.xml in dev mode
            // The ServerConfigXmlDocument will create the directories if needed.
            generatedXmlFile = new File(project.getLayout().getBuildDirectory().getAsFile().get(), GENERATED_FEATURES_TEMP_PATH);
        } else {
            generatedXmlFile = new File(generationContextDir, GENERATED_FEATURES_FILE_PATH);
        }
        // For standalone goal (not dev mode) with generateToSrc=true, also write to server dir if it exists
        File serverDirectory = getServerDir(project);
        boolean shouldWriteToServerDir = !isDevMode && generateToSrc && (serverDirectory != null) && serverDirectory.exists();
        File serverDirXmlFile = null;
        if (shouldWriteToServerDir) {
            serverDirXmlFile = new File(serverDirectory, GENERATED_FEATURES_FILE_PATH);
        }
        try {
            if (missingLibertyFeatures.size() > 0) {
                Set<String> existingGeneratedFeatures = getGeneratedFeatures(servUtil, generatedXmlFile);
                if (!missingLibertyFeatures.equals(existingGeneratedFeatures)) {
                    // Create specialized server.xml
                    ServerConfigXmlDocument configDocument = ServerConfigXmlDocument.newInstance();
                    configDocument.createComment(HEADER);
                    Element featureManagerElem = configDocument.createFeatureManager();
                    configDocument.createComment(featureManagerElem, GENERATED_FEATURES_COMMENT);
                    for (String missing : missingLibertyFeatures) {
                        logger.debug(String.format("Adding missing feature %s to %s.", missing, GENERATED_FEATURES_FILE_PATH));
                        configDocument.createFeature(missing);
                    }
                    // Output log messages before writing file as the file change event kicks off other dev mode actions
                    logger.lifecycle("Generated the following features: " + missingLibertyFeatures);
                    printCommonMessages(eeVersion, mpVersion, generatedXmlFile);
                    // use logger.lifecycle so that message appears without --info tag on
                    configDocument.writeXMLDocument(generatedXmlFile);
                    logger.debug("Created file " + generatedXmlFile);

                    // For standalone mode with generateToSrc=true, also write to server directory
                    if (shouldWriteToServerDir) {
                        if (writeToServerDir(configDocument, serverDirXmlFile, true)) {
                            logger.debug("Also created file " + serverDirXmlFile);
                        }
                    }
                } else {
                    logger.lifecycle("No change to the generated feature list: " + missingLibertyFeatures);
                    printCommonMessages(eeVersion, mpVersion, generatedXmlFile);
                    // use logger.lifecycle so that message appears without --info tag on
                }
            } else {
                logger.lifecycle("No additional features were generated.");
                if (generatedXmlFile.exists()) {
                    // generated-features.xml exists but no additional features were generated
                    // create empty features list with comment
                    ServerConfigXmlDocument configDocument = ServerConfigXmlDocument.newInstance();
                    configDocument.createComment(HEADER);
                    Element featureManagerElem = configDocument.createFeatureManager();
                    configDocument.createComment(featureManagerElem, NO_NEW_FEATURES_COMMENT);
                    configDocument.writeXMLDocument(generatedXmlFile);

                    // For standalone mode with generateToSrc=true, also write to server directory
                    if (shouldWriteToServerDir) {
                        writeToServerDir(configDocument, serverDirXmlFile, serverDirXmlFile.exists());
                    }
                }
            }
        } catch (ParserConfigurationException | TransformerException | IOException e) {
            logger.debug("Exception creating the server features file", e);
            throw new GradleException("Automatic generation of features failed. Error attempting to create the " + GENERATED_FEATURES_FILE_NAME + ". Ensure your ID has write permission to the server installation directory.", e);
        }
    }

    /*
     * This method prints the output for both cases when features are generated (i.e., new features were generated or the same set)
     */
    private void printCommonMessages(String eeVersion, String mpVersion, File generatedXmlFile) {
        logger.lifecycle("The generated feature list has been written to the following file: " + generatedXmlFile.getAbsolutePath());
        if (eeVersion == null && mpVersion == null) {
            logger.lifecycle("Verify the generated feature list meets the needs of your application." +
                " If you see features missing or features at unexpected versions, please add the expected features to your server configuration" +
                (isDevMode ? "." : " and run the generateFeatures task again."));
        }
    }

    private boolean writeToServerDir(ServerConfigXmlDocument configDocument, File serverDirXmlFile, boolean exists) {
        if (exists) {
            try {
                configDocument.writeXMLDocument(serverDirXmlFile);
            } catch (TransformerException | IOException e) {
                logger.warn("Failed to write generated-features.xml to server directory: "
                    + serverDirXmlFile.getAbsolutePath() + ". Ensure your ID has write permission to the server configuration directory. "
                    + "Message from the Exception: " + e.getMessage());
                return false;
            }
        }
        return true;
    }

    // Get the features from the server config and optionally exclude the specified config files from the search.
    private Set<String> getServerFeatures(ServerFeatureUtil servUtil, Set<String> generatedFiles, boolean excludeGenerated) {
        return getServerFeaturesPlatforms(servUtil, generatedFiles, excludeGenerated, true);
    }
    private Set<String> getServerPlatforms(ServerFeatureUtil servUtil, Set<String> generatedFiles, boolean excludeGenerated) {
        return getServerFeaturesPlatforms(servUtil, generatedFiles, excludeGenerated, false); // platforms
    }

    // Get the features from the server config and optionally exclude the specified config files from the search.
    private Set<String> getServerFeaturesPlatforms(ServerFeatureUtil servUtil, Set<String> generatedFiles, boolean excludeGenerated, boolean features) {
        servUtil.setLowerCaseFeatures(false);
        // if optimizing, ignore generated files when passing in existing features to feature generator
        FeaturesPlatforms fp = servUtil.getServerFeatures(generationContextDir, server.serverXmlFile, new HashMap<String, File>(), excludeGenerated ? generatedFiles : null); // pass generatedFiles to exclude them
        servUtil.setLowerCaseFeatures(true);
        if (fp == null) {
            return new HashSet<String>();
        } else if (features) {
            return fp.getFeatures();
        } // else
        return fp.getPlatforms();
    }

    // returns the features specified in the generated-features.xml file
    private Set<String> getGeneratedFeatures(ServerFeatureUtil servUtil, File generatedFeaturesFile) {
        servUtil.setLowerCaseFeatures(false);
        FeaturesPlatforms fp = servUtil.getServerXmlFeatures(new FeaturesPlatforms(), generationContextDir,
                generatedFeaturesFile, null, null);
        Set<String> genFeatSet = fp == null ? new HashSet<String>() : fp.getFeatures();
        servUtil.setLowerCaseFeatures(true);
        return genFeatSet;
    }

    // returns the hidden directory we use for generate-features special purposes
    private File getGeneratedFeaturesTempDir() {
        return new File(project.getLayout().getBuildDirectory().getAsFile().get(), GENERATED_FEATURES_TEMP_DIR);
    }

    /**
     * Gets the feature generator jar file from the local cache.
     * Downloads it first from connected repositories such as Maven Central if a newer release is available than the cached version.
     * Note: Maven updates artifacts daily by default based on the last updated timestamp. Users should use 'mvn -U' to force updates if needed.
     *
     * @return The File object of the feature-gen.jar in the local cache.
     * @throws PluginExecutionException indicates the feature-gen.jar could not be found
     */
    private File getFeatureGenJarFromRepository() throws PluginExecutionException {
        try {
            return ArtifactDownloadUtil.downloadBuildArtifact(project, FEATURE_GEN_MAVEN_GROUP_ID, FEATURE_GEN_MAVEN_ARTIFACT_ID, FEATURE_GEN_MAVEN_TYPE, FEATURE_GEN_MAVEN_VERSION);
        } catch (Exception e) {
            throw new PluginExecutionException("Could not retrieve the artifact " + FEATURE_GEN_MAVEN_GROUP_ID + "."
                    + FEATURE_GEN_MAVEN_ARTIFACT_ID + "." + FEATURE_GEN_MAVEN_VERSION
                    + " needed for generateFeatures. Ensure you have a connection to Maven Central or another repository that contains the "
                    + FEATURE_GEN_MAVEN_GROUP_ID + "." + FEATURE_GEN_MAVEN_ARTIFACT_ID
                    + ".jar configured in your build.gradle.",
                    e);
        }
    }

    /*
     * Gets the file containing the Open Liberty base feature list from the local cache.
     * Downloads it first from connected repositories such as Maven Central if a newer release is available than the cached version.
     * Note: Maven updates artifacts daily by default based on the last updated timestamp. Users should use 'mvn -U' to force
     * updates if needed.
     * 
     * @return The File object of the feature list in the local cache or null if version number not available
     */
    private static String OPEN_LIBERTY_FEATURE_LIST_START = "25.0.0.7";
    private File getOpenFeatureListFile() {
        String libertyVersion = getLibertyRuntimeVersion();
        if (libertyVersion == null) {
            return null;
        }
        // Feature lists were first published for 25.0.0.7. For liberty releases prior to this simply use the
        // earliest available feature list, 25.0.0.7.
        if (VersionUtility.compareArtifactVersion(libertyVersion, OPEN_LIBERTY_FEATURE_LIST_START, true) < 0) {
            libertyVersion = OPEN_LIBERTY_FEATURE_LIST_START;
        }
        libertyVersion = "[" + libertyVersion + "]"; // Maven syntax to specify an exact version, not a range
        return ArtifactDownloadUtil.downloadBuildArtifact(project, OLBASE_FEATURELIST_GROUP_ID, OLBASE_FEATURELIST_ARTIFACT_ID, OLBASE_FEATURELIST_TYPE, libertyVersion);
    }

    /*
     * Gets the file containing the indicated Websphere feature list from the local cache.
     * Downloads it first from connected repositories such as Maven Central if a newer release is available than the cached version.
     * Note: Maven updates artifacts daily by default based on the last updated timestamp. Users should use 'mvn -U' to force
     * updates if needed.
     * 
     * @return The File object of the feature list in the local cache.
     */
    private static String FEATURE_LIST_BASE = "base";
    private static String FEATURE_LIST_CORE = "core";
    private File getWebSphereFeatureListFile(String featureListVar) {
        // For releases earlier than 25.0.0.7 use 25.0.0.7 Maven coordinates (batch 1).
        // For releases 25.0.0.8 to 25.0.0.12 use batch 2 coordinates. 
        // For 26.0.0.1 and later use the third batch.
        String libertyGroupId, libertyArtifactId;
        String libertyVersion = getLibertyRuntimeVersion();
        if (libertyVersion == null) {
            return null;
        }
        // Publishing started with 25.0.0.7 so for any liberty <25.0.0.7 use the 07 values
        if (VersionUtility.compareArtifactVersion(libertyVersion, WS_FEATURE_LIST_VERSION_BATCH1, true) <= 0) {
            libertyGroupId = WS_FEATURELIST_GROUP_ID_BATCH1;
            libertyArtifactId = (featureListVar.equals(FEATURE_LIST_BASE)) ? WS_BASE_FEATURE_LIST_ARTIFACT_ID_BATCH1 : WS_CORE_FEATURE_LIST_ARTIFACT_ID_BATCH1;
            libertyVersion = WS_FEATURE_LIST_VERSION_BATCH1; // must set for versions before 07
        } else if (VersionUtility.compareArtifactVersion(libertyVersion, WS_FEATURE_LIST_VERSION_BATCH3, true) < 0) {
            // 25.0.0.8 to 25.0.0.12
            libertyGroupId = WS_FEATURELIST_GROUP_ID_BATCH2;
            libertyArtifactId = (featureListVar.equals(FEATURE_LIST_BASE)) ? WS_BASE_FEATURE_LIST_ARTIFACT_ID_BATCH2 : WS_CORE_FEATURE_LIST_ARTIFACT_ID_BATCH2;
        } else { // 26.0.0.1 and up
            libertyGroupId = WS_FEATURELIST_GROUP_ID_BATCH3;
            libertyArtifactId = (featureListVar.equals(FEATURE_LIST_BASE)) ? WS_BASE_FEATURE_LIST_ARTIFACT_ID_BATCH3 : WS_CORE_FEATURE_LIST_ARTIFACT_ID_BATCH3;
        }
        libertyVersion = "[" + libertyVersion + "]"; // Maven syntax to specify an exact version, not a range
        getLog().debug("WebSphere Liberty feature list coordinates, libertyGroupId="+libertyGroupId+" libertyArtifactId="+libertyArtifactId+" WS_FEATURELIST_TYPE="+WS_FEATURELIST_TYPE+" libertyVersion="+libertyVersion);
        return ArtifactDownloadUtil.downloadBuildArtifact(project, libertyGroupId, libertyArtifactId, WS_FEATURELIST_TYPE, libertyVersion);
    }

    // resolve the Liberty version from one of the sources
    private String getLibertyRuntimeVersion() {
        String libertyRuntimeVersion = null
        Configuration config = project.configurations.getByName('libertyRuntime')
        if (config != null) {
             config.dependencies.find { libertyArtifact ->
                 libertyRuntimeVersion = libertyArtifact.version
                 logger.debug 'Found Liberty runtime version: ' + libertyRuntimeVersion
                 return true
             }
        }
        return libertyRuntimeVersion
    }

    // resolve the Liberty version from one of the sources
    private String getLibertyRuntimeGroupId() {
        String libertyRuntimeGroupId = null
        Configuration config = project.configurations.getByName('libertyRuntime')
        if (config != null) {
             config.dependencies.find { libertyArtifact ->
                 libertyRuntimeGroupId = libertyArtifact.group
                 logger.debug 'Found Liberty runtime group ID: ' + libertyRuntimeGroupId
                 return true
             }
        }
        return libertyRuntimeGroupId
    }

    private Set<String> getClassesDirectories() {
        Set<String> classesDirectories = new ArrayList<String>();
        project.sourceSets.main.getOutput().getClassesDirs().each {
            if (it.exists()) {
                classesDirectories.add(it.getAbsolutePath());
            }
        }
        return classesDirectories;
    }

    /**
     * Return the latest EE major version detected in the project dependencies
     *
     * @param project
     * @return latest EE major version corresponding to the EE umbrella dependency, null if an EE umbrella dependency is not found
     */
    private static final String JAKARTA_PLATFORM_NAME="jakartaee-"; // jakartaee-10.0 etc.
    private static final String JAVAEE_PLATFORM_NAME="javaee-"; // javaee-7.0 etc.
    protected getEEVersion(Object project, ServerFeatureUtil servUtil) {
        Set<String> eeVersionsDetected = new HashSet<String>();
        logger.warn("getEEVersion")
        // compileClasspath is the correct scope for the dependencies so no need to check scope separately like in Maven
        project.configurations.compileClasspath.allDependencies.each {
            dependency ->
                if ((dependency.group.equals("javax") && dependency.name.equals("javaee-api")) ||
                    (dependency.group.equals("jakarta.platform") &&
                        (dependency.name.equals("jakarta.jakartaee-api") ||
                        dependency.name.equals("jakarta.jakartaee-web-api") ||
                        dependency.name.equals("jakarta.jakartaee-core-api") ||
                        dependency.name.equals("jakarta.jakartaee-bom") ||
                        dependency.name.equals("jakartaee-api-parent")))) {
                    if (dependency.version != null) {
                        logger.debug("Java and/or Jakarta EE umbrella dependency version: " + dependency.version + " found in project");
                        logger.warn ("Java and/or Jakarta EE umbrella dependency version: " + dependency.version + " found in project");
                        eeVersionsDetected.add(dependency.version);
                    }
                }
        }
        // If there are no dependencies try looking at server.xml for platform entries
        if (eeVersionsDetected.size() == 0) {
            // Gather all Jakarta EE platform versions
            eeVersionsDetected.addAll(getAllPlatformVersions(JAKARTA_PLATFORM_NAME, servUtil));
            // Gather all Java EE platform versions
            eeVersionsDetected.addAll(getAllPlatformVersions(JAVAEE_PLATFORM_NAME, servUtil));
            // return the maximum version from all platforms
        }
        String eeVersion = findMaxVersion(eeVersionsDetected);
        if (eeVersionsDetected.size() > 1) {
            logger.lifecycle("Multiple Java EE and/or Jakarta EE versions found, using the latest version (" +
                eeVersion + ") found to generate Liberty features.");
        }
        return eeVersion;
    }

    /**
     * Returns the latest MicroProfile major version detected in the project dependencies
     *
     * @param project
     * @return latest MP major version corresponding to the MP umbrella dependency, null if an MP umbrella dependency is not found
     */
    private static final String MP_PLATFORM_NAME="microProfile-"; // microProfile-7.0 etc.
    protected getMPVersion(Object project, ServerFeatureUtil servUtil) {
        Set<String> mpVersionsDetected = new HashSet<String>();
        project.configurations.compileClasspath.allDependencies.each {
            dependency ->
                if (dependency.group.equals("org.eclipse.microprofile") &&
                        dependency.name.equals("microprofile")) {
                    if (dependency.version != null) {
                        logger.debug("MicroProfile umbrella dependency version: " + dependency.version + " found in project");
                        logger.warn ("MicroProfile umbrella dependency version: " + dependency.version + " found in project");
                        mpVersionsDetected.add(dependency.version);
                    }
                }
        }
        // If there are no dependencies try looking at server.xml for platform entries
        if (mpVersionsDetected.size() == 0) {
            mpVersionsDetected.addAll(getAllPlatformVersions(MP_PLATFORM_NAME, servUtil));
        }
        String mpVersion = findMaxVersion(mpVersionsDetected);
        if (mpVersionsDetected.size() > 1) {
            logger.lifecycle("Multiple MicroProfile versions found, using the latest version (" +
                mpVersion + ") found to generate Liberty features.");
        }
        return mpVersion;
    }

    /**
     * Find the highest version number in the set of strings
     * returns null if the set of strings is empty
    */
    private String findMaxVersion(Set<String> versionsDetected) {
        String maxVersion = null;
        if (!versionsDetected.isEmpty()) {
            maxVersion = versionsDetected.iterator().next();
            if (versionsDetected.size() == 1) {
                return maxVersion;
            }
            ComparableVersion cMaxVersion = new ComparableVersion(maxVersion);
            // if multiple EE/MP versions are found across multiple modules, return the latest version
            for (String ver : versionsDetected) {
                ComparableVersion cVer = new ComparableVersion(ver);
                logger.debug("GenerateFeraturesTask.findMaxVersion, ver=" + ver);
                if (cVer.compareTo(cMaxVersion) > 0) {
                    maxVersion = ver;
                    cMaxVersion = cVer;
                }
            }
        }
        return maxVersion;
    }

    // Retrieve all platforms from the server.xml and related files that match the platform specified.
    // Platforms have the format jakartaee-10.0 or microProfile-7.1. Return all version numbers (10.0, 7.1, etc.) that match.
    private Set<String> getAllPlatformVersions(String platformName, ServerFeatureUtil servUtil) {
        Set<String> platformVersions = new HashSet<String>();
        Set<String> platforms = getServerPlatforms(servUtil, null, false);
        for (String p : platforms) {
            logger.debug("GenerateFeaturesMojo.getAllPlatformVersions, searching for platform:" + platformName + " platform=" + p);
            if (p.startsWith(platformName)) {
                platformVersions.add(p.substring(platformName.length()));
            }
        }
        return platformVersions;
    }

    // Retrieve all platforms from the server.xml and related files that match the platform specified.
    // Platforms have the format jakartaee-10.0 or microProfile-7.1. Return all version numbers (10.0, 7.1, etc.) that match.
    private Set<String> getAllPlatformVersions(String platformName, ServerFeatureUtil servUtil) {
        Set<String> platformVersions = new HashSet<String>();
        Set<String> platforms = getServerPlatforms(servUtil, null, false);
        for (String p : platforms) {
            logger.debug("GenerateFeaturesTask.getAllPlatformVersions, searching for platform:" + platformName + " platform=" + p);
            if (p.startsWith(platformName)) {
                platformVersions.add(p.substring(platformName.length()));
            }
        }
        return platformVersions;
    }

    // Define the logging functions of the feature generator handler and make it available in this plugin
    private class FeatureGenHandler extends FeatureGeneratorUtil {
        FeatureGenHandler(File generatorFile) {
            super(generatorFile);
        }

        @Override
        public void debug(String msg) {
            logger.debug(msg);
        }

        @Override
        public void debug(String msg, Throwable t) {
            logger.debug(msg, t);
        }

        @Override
        public void error(String msg) {
            logger.error(msg);
        }

        @Override
        public void warn(String msg) {
            logger.warn(msg);
        }

        @Override
        public void info(String msg) {
            logger.lifecycle(msg);
        }

        @Override
        public boolean isDebugEnabled() {
            return logger.isEnabled(LogLevel.DEBUG);
        }
    }
}
